# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: c
# language: objective-c

env:
  - R_BUILD_ARGS=" "
script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cp scripts/travis-tool.sh fakepackage
  - cd fakepackage
  - ./travis-tool.sh bootstrap
after_success:
  - ./travis-tool.sh dump_logs_by_extension out
after_failure:
  - ./travis-tool.sh dump_logs
install:
  - ./travis-tool.sh install_deps
  # TESTS
  #
  # The following lines exist to test various features of our travis
  # scripts; don't use these as a model for other `.travis.yml` files.
  # Test aptget_install with multiple arguments.
  - ./travis-tool.sh aptget_install tmux psmisc
  - test -n "$(which tmux)"
  - test -n "$(which killall)"
  # Test r_install (which accepts multiple arguments).
  - ./travis-tool.sh r_install stringr lubridate
  - Rscript -e 'library(stringr); library(lubridate)'
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
  - Rscript -e 'library(assertthat); library(testthat)'
  - ./travis-tool.sh r_binary_install RUnit survey
  - Rscript -e 'library(RUnit); library(survey)'
