# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: c
# language: objective-c

script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cp scripts/travis-tool.sh fakepackage
  - cd fakepackage
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh aptget_install tmux
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
